title: Bibi Can Fly
description: >
  Leghosszabb "nyaralásunk" - avagy két mérnök Új-Zélandon Working Holiday Vízummal.
facebook_username: BibiCanFly

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
